<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnJ3xlY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnJ3xlY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFnJ3xlY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFnJ3xlY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFnJ3xlY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FnJ3xlY',
    'container.build_id' => 'd016d2d4',
    'container.build_time' => 1584902889,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnJ3xlY');
